name: Publish
on: [push]
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install NPM Packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --production

    - name: Static Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
      env:
        NODE_ENV: production
        GHOST_API_URL: ${{ secrets.ghost_api_url }}
        GHOST_CONTENT_API_KEY: ${{ secrets.ghost_content_api_key }}

    - name: Set CNAME
      run: |
        sudo tee -a public/CNAME > /dev/null << EOF
        gracelead.org
        EOF
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
